### ISSUE TITLE
Передача объектов в УДЯ

### ISSUE THREAD

**Issue by AirAlarm** [and7ey/haier_evo#27]
Добрый день! Плагин работает, все отлично, в т.ч. и с УДЯ. Вопрос, можно ли вручную настроить частоту обновления данных с датчиков блоков? Умный дом Яндекса периодически жалуется на долгое отсутствие данных от устройств, решается переходом в карточку устройства. На работоспособность не влияет, скорее, косметическое неудобство. 

![image](https://github.com/user-attachments/assets/3c933876-e2ca-4ee4-ac14-8f0f1101ddbe)
![image](https://github.com/user-attachments/assets/c90a3b07-5ba6-43d3-afa2-0a2fe2b2b69b)
![image](https://github.com/user-attachments/assets/bb6999aa-b89e-43eb-881b-d84611baa960)

**Comment by q9957789** [comment]
гораздо проще прорастить все в удя из evo через официальную интеграцию и от туда в ha через https://github.com/AlexxIT/YandexStation

**Comment by rleschuk** [comment]
для того чтобы кондиционер нормально отображался в УДЯ нужно прописать в configuration.yaml
```
yandex_smart_home:
  entity_config:
    идендификатор_кондиционера_в_ха:
      type: thermostat.ac
      turn_on:
        action: climate.turn_on
        entity_id: идендификатор_кондиционера_в_ха
```
